name: build

on:
  push:
    branches:
      - main

jobs:
  build-and-push-images:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get timestamp
        id: get_time
        run: echo "TIMESTAMP=$(date '+%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/server:${{ env.TIMESTAMP }}
            ghcr.io/${{ github.repository }}/server:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/server:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/server:buildcache,mode=max
